name: test_products_and_cart
description: Test project. Mock app. 
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <3.24.5'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.2.3
  dio: ^5.7.0
  connectivity_plus: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13


flutter:
  uses-material-design: true

  generate: true

